version: '3'
services:
    docker-jenkins:
        container_name: docker-jenkins
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
            - "50000:50000"
    mailhog:
        container_name: mailhog
        image: mailhog/mailhog
        ports:
            - "8025:8025"
